
[application]
name = "DMW3 Randomizer"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "DMW3 Randomizer"
base_path = ""

[web.resource]
style = [
	"./assets/style.css"
]
script = []

[web.resource.dev]

[web.watcher]