
[application]
name = "DMW3 Randomizer"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "DMW3 Randomizer"

[web.resource]
style = [
	"./assets/style.css"
]
script = []

[web.resource.dev]

[web.watcher]

[bundle]
icon = [
	"icons/32x32.png",
	"icons/128x128@2x.png",
	"icons/icon.icns",
	"icons/icon.ico",
	"icons/Square30x30Logo.png",
	"icons/Square44x44Logo.png",
	"icons/Square71x71Logo.png",
	"icons/Square89x89Logo.png",
	"icons/Square107x107Logo.png",
	"icons/Square142x142Logo.png",
	"icons/Square150x150Logo.png",
	"icons/Square284x284Logo.png",
	"icons/Square310x310Logo.png"
]
