name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends build-essential ninja-build libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Cargo bundle
      run: cargo install cargo-bundle
    - name: Build mkpsxiso
      run: |
        cmake --preset ci -S ./mkpsxiso -B ./mkpsxiso/build
        cmake --build ./mkpsxiso/build --config Release
    - name: Build
      run: cargo build --verbose --release
    - name: Bundle
      run: cargo bundle --release --format deb
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dmw3-randomizer-linux
        path: target/release/bundle/deb/*.deb
  
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose --release
    - name: Build mkpsxiso
      run: |
        cmake --preset ci -S ./mkpsxiso -B ./mkpsxiso/build -G "Visual Studio 17 2022"
        cmake --build ./mkpsxiso/build --config Release
    - name: Construct artifact
      run: |
        mkdir artifact
        xcopy assets\ artifact\assets /i
        xcopy target\release\*.exe artifact\
        xcopy mkpsxiso\build\Release\*.exe artifact\
        Compress-Archive -Path artifact\* -DestinationPath dmw3-randomizer-windows.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dmw3-randomizer-windows
        path: dmw3-randomizer-windows.zip

  create-release:
    name:    Create release
    runs-on: ubuntu-latest
    needs:   [ build-windows, build-linux ]
  
    steps:
    - name: Fetch build artifacts
      if:   ${{ github.ref_type == 'tag' }}
      uses: actions/download-artifact@v3
      with:
        path: .
  
    - name: Publish release
      if:   ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          dmw3-randomizer-linux/*
          dmw3-randomizer-windows/*
