name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends build-essential ninja-build libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Cargo bundle
      run: cargo install cargo-bundle
    - name: Build mkpsxiso
      run: |
        cmake -S ./mkpsxiso -B ./mkpsxiso/build -DCMAKE_BUILD_TYPE=Release
        cmake --build ./mkpsxiso/build
    - name: Build
      run: cargo build --verbose --release
    - name: Bundle
      run: cargo bundle --release --format deb
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dmw3-randomizer-linux
        path: target/release/bundle/deb/*.deb
  
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Cargo bundle
      run: cargo install cargo-bundle
    - name: Build mkpsxiso
      run: |
        cmake -S ./mkpsxiso -B ./mkpsxiso/build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
        cmake --build ./mkpsxiso/build
    - name: Build
      run: cargo build --verbose --release
    - name: Bundle
      run: cargo bundle --release --format msi
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dmw3-randomizer-windows
        path: target/release/bundle/msi/*.msi


