name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends build-essential ninja-build libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
    - uses: actions/checkout@v3
    - name: Install Cargo bundle
      run: cargo install cargo-bundle
    - name: Build
      run: cargo build --verbose --release
    - name: Bundle
      run: cargo bundle --release --format deb
